### ISSUE TITLE
index.js is lost

### ISSUE THREAD

**Issue by sanpago** [AlbanMinassian/nodejs-yapaginate#1]
packages.json references index.js in its main section, but this files does no exists.

So, when nodejs-yapaginate is required, I get this error:

$ node

> v = require("nodejs-yapaginate")
> Error: Cannot find module 'nodejs-yapaginate'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:362:17)
>     at require (module.js:378:17)
>     at repl:1:6
>     at REPLServer.self.eval (repl.js:109:21)
>     at Interface.<anonymous> (repl.js:248:12)
>     at Interface.EventEmitter.emit (events.js:96:17)
>     at Interface._onLine (readline.js:200:10)
>     at Interface._line (readline.js:518:8)

**Comment by sanpago** [comment]
Solved using: require('nodes-yapaginate/lib/main.js');
